version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Hello123
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  smtp:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres-db:
    driver: local
